version: '3.8'

services:
  rag-api-dev:
    build: .
    ports:
      - "8000:8080"
    env_file:
      - .env
    volumes:
      - ./src:/app/src  # Live code changes
      - ./tests:/app/tests  # Test files
      - ./documents:/app/documents:ro  # Mount documents for ingestion
      - ./vector_store:/app/vector_store  # Persist local vector store
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload --log-level debug
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 