version: '3.8'

services:
  rag-api:
    build: .
    ports:
      - "8000:8080"
    env_file:
      - .env
    volumes:
      - ./documents:/app/documents:ro  # Mount documents for ingestion
      - ./vector_store:/app/vector_store  # Persist local vector store
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5' 