name: RAG Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    name: Run Tests and Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run linter
        run: |
          flake8 src/ tests/
          black --check src/ tests/

      - name: Run tests
        run: |
          pytest

  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test-and-lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          # This is now filled with your correct project details
          workload_identity_provider: 'projects/508052440393/locations/global/workloadIdentityPools/github-pool/providers/github-actions-provider-v2'
          service_account: 'github-actions-sa@rag-project-v3.iam.gserviceaccount.com'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for GCP Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # This now points to your new project's Artifact Registry
          tags: us-central1-docker.pkg.dev/rag-project-v3/rag-project-repo/rag-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max